<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Simple Stock | <?= $pagename ?></title>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>

        <script type="text/javascript" src="/js/jquery-3.0.0.min.js"></script>
        <script type="text/javascript" src="/js/underscore-min.js"></script>
        <script type="text/javascript" src="/js/backbone-min.js"></script>
    </head>
    <body>
        <h1>Simple Stock</h1>
        <div>Aplicación simple para control de inventarios</div>
    </body>
</html>
