<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $pagename ?></title>

        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no">

        <link rel="stylesheet" type="text/css" href="/css/materialize.min.css">
        <link rel="stylesheet" type="text/css" href="/css/app.css">

        <?php foreach (glob(__DIR__.'/../app/templates/*.html') as $key => $filename) include_once $filename; ?>

        <!--script type="text/javascript" src="/js/jquery-2.2.2.min.js"></script-->
        <script type="text/javascript" src="/js/jquery-3.0.0.min.js"></script>
        <script type="text/javascript" src="/js/underscore-min.js"></script>
        <script type="text/javascript" src="/js/backbone-min.js"></script>
        <script type="text/javascript" src="/js/materialize.min.js"></script>

        <script type="text/javascript" src="/js/app.js"></script>
    </head>
    <body>
        
    </body>
</html>